### ISSUE TITLE
touchscreen fails on Chuwi Hi10 Pro (CW1529)

### ISSUE THREAD

**Issue by ssinyagin** [hopkinskong/linux_cherrytrail#2]
Chuwi Hi10 Pro tablet with Atom x5-Z8350, linux_cherrytrail
 patches at 3dd7325.
Touch screen doesn't work, and the following is seen in dmesg:
```
[   10.456998] axp20x-i2c i2c-INT33F4:00: AXP20x variant AXP288 found
[   10.485335] silead_ts i2c-MSSL1680:00: Chip ID read error -121
[   10.507849] ACPI Exception: AE_ERROR, Returned by Handler for [GeneralPurposeIo] (20160930/evregion-300)
[   10.507871] ACPI Error: Method parse/execution failed [\_SB.PCI0.I2C6.TCS1._PS3] (Node ffff997d3b0c9190), AE_ERROR (20160930/psparse-543)
[   10.507896] acpi MSSL1680:00: Failed to change power state to D3hot
[   10.507985] silead_ts: probe of i2c-MSSL1680:00 failed with error -121
[   10.512941] axp20x-i2c i2c-INT33F4:00: AXP20X driver loaded
[   10.602987] SSE version of gcm_enc/dec engaged.
[   10.818870] intel_rapl: Found RAPL domain package
[   10.818874] intel_rapl: Found RAPL domain core
[   11.178735] input: axp20x-pek as /devices/pci0000:00/808622C1:06/i2c-14/i2c-INT33F4:00/axp20x-pek/input/input6
```

**Comment by hopkinskong** [comment]
You are not using my added ACPI version of touchscreen driver, as seen from dmesg, the driver name is `silead_ts`, instead of `gslx680`.

Please re-run `make menuconfig`, disable the touchscreen driver (saying N), then the ACPI version of the driver will appear, please say M on that driver.

Please note that you need to obtain the firmware of the touchscreen at https://github.com/onitake/gsl-firmware, or extract it by yourself from existing android/windows driver.

**Comment by ssinyagin** [comment]
thanks, now building with explicit `CONFIG_TOUCHSCREEN_SILEAD=n`

**Comment by ssinyagin** [comment]
Also I wonder how it will deal with a rotated screen

**Comment by ssinyagin** [comment]
Where should I place the firmware file?

**Comment by ssinyagin** [comment]
by the way, ubuntu, and I guess all other distributions, don't really like when a hardware module is removed from the kernel. Is there a way not to remove `silead`?

**Comment by ssinyagin** [comment]
it finally compiled, and the screen reacts on touch. But the cursor moves in an opposite direction from my finger :)
So, it needs a bit of work on calibrating the whole stuff.

**Comment by ssinyagin** [comment]
on my CW1529 (Chuwi Hi10 Pro), I could not make the touchscreen work properly. maximum that I could achieve is that the touchscreen works in the lower 1/4 part of the screen, but in the rest of the area the cursor is jumping randomly. Also the driver does not take the screen orientation into consideration.

So, for "normal" orientation, which is vertical by default, the best result is achieved with
```
perl -I tools/ ./tools/fwtool -c firmware/chuwi/hi10_pro/firmware.fw -m 1680 -w 1260 -h 1925 -t 5 -f track,swap /lib/firmware/silead_ts.fw
```

If I do `xrandr -o right`, and the screen is usable with the docked keyboard, the firmware needs different parameters:
```
perl -I tools/ ./tools/fwtool -c firmware/chuwi/hi10_pro/firmware.fw -m 1680 -w 1925 -h 1260 -t 5 -f track,yflip /lib/firmware/silead_ts.fw
```

Is there a way to debug the thing?

**Comment by hopkinskong** [comment]
@ssinyagin Try extract another fw (if there is) for your device.
You should also get your screen orientation right before generating firmware for your touch screen.
Btw, issue regarding the touchscreen should be reported to https://github.com/onitake/gslx680-acpi

**Comment by ssinyagin** [comment]
thanks, reopened at https://github.com/onitake/gslx680-acpi/issues/20
